FIX: (NONE) 차량 고유 ID 누락 수정
teamo2dev/gotar-rentcar-interface pull request #14
Opened 2024-06-03 02:20 UTC by SJY0917032

- 차량 고유 ID부분에 구분자가 누락이 된 부분이 있어 수정 했습니다.

2024-06-03 18:38 UTC, peter-huvenet requested changes

2024-06-03 18:38 UTC, peter-huvenet commented on Vehicle.ts
>     * - Available: BG_와 같이 API Identifier + 차량에대한 고유함을 보장할 수 있는 조합 값
여기도 차종으로 수정

2024-06-03 18:38 UTC, peter-huvenet commented on Vehicle.ts
>     * - Available: BG_와 같이 API Identifier + 차량에대한 고유함을 보장할 수 있는 조합 값
여기도 수정해주세요.

2024-06-04 01:48 UTC, SJY0917032 commented on Vehicle.ts
>     * - Available: BG_와 같이 API Identifier + 차량에대한 고유함을 보장할 수 있는 조합 값
- [ ] 오타 수정

2024-06-04 01:48 UTC, SJY0917032 commented on Vehicle.ts
>     * - Available: BG_와 같이 API Identifier + 차량에대한 고유함을 보장할 수 있는 조합 값
- [ ] 오타 수정

2024-06-24 16:23 UTC, peter-huvenet approved these changes

2024-06-25 05:42 UTC, merged