FEAT: (NONE) v2.3
teamo2dev/gotar-rentcar-interface pull request #15
Opened 2024-06-24 06:14 UTC by SJY0917032

- 차량 리스트 검색시 일정 범위의 반경만 조회할 수 있도록 Request Parameter값이 추가 됐습니다.
  - 해당 값은 기본값이 10km이며, 해당 값으로 받은 좌표값 기준 반경 N km를 조회한 값을 반환해야합니다.

2024-06-24 16:25 UTC, peter-huvenet requested changes

2024-06-24 16:25 UTC, peter-huvenet commented on APIs/DTO/Request/VehicleListRequest.ts
> +   * @requried true
@nullable true
@required false
로 하는게 좋을 것 같습니다.

2024-06-24 16:25 UTC, peter-huvenet commented on APIs/DTO/Request/VehicleListRequest.ts
> +   * @requried true
required 오타입니다.

2024-06-25 02:31 UTC, SJY0917032 commented on APIs/DTO/Request/VehicleListRequest.ts
> +   * @requried true
- [ ] 스펙변경

2024-06-25 02:31 UTC, SJY0917032 commented on APIs/DTO/Request/VehicleListRequest.ts
> +   * @requried true
- [ ] 오타 수정

2024-06-25 14:07 UTC, peter-huvenet approved these changes

2024-07-08 04:29 UTC, merged